name: Bit export CI

on:
  release:
    types: [published]

jobs:
  bit-export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
       token: ${{ secrets.PAT }}
    - uses: actions/setup-node@v2
      with:
       node-version: '14.x'
    - run: git checkout master
    - name: Install Bit Version Manager 
      run: npm i -g @teambit/bvm
    - name: Install latest Bit version 
      run: bvm install
    - name: add bvm bin folder to path
      run: echo "$HOME/bin" >> $GITHUB_PATH
    - name: Set up bit config
      run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
    - name: Install packages using bit
      run: bit install
    - name: Hard-tag pending components
      run: bit tag --persist
    - name: Export components
      run: bit export
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
       commit_message: Updated bitmap file